name: Fully Automated Build and Sign APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Generate Keystore Automatically
      run: |
        keytool -genkey -v -keystore app/upload-keystore.jks \
        -alias weatherkey -keyalg RSA -keysize 2048 -validity 10000 \
        -storepass android123456 -keypass android123456 \
        -dname "CN=Weather App, OU=Development, O=Android, L=Tehran, C=IR"

    - name: Build Signed Release APK
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease \
        -Pandroid.injected.signing.store.file=upload-keystore.jks \
        -Pandroid.injected.signing.store.password=android123456 \
        -Pandroid.injected.signing.key.alias=weatherkey \
        -Pandroid.injected.signing.key.password=android123456

    - name: Upload Signed APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: fully-signed-app
        path: app/build/outputs/apk/release/app-release.apk
